#!/bin/bash
# This file is part of universal business adapter
#
# AUTHORS
#     Sven Herzberg  <sven@imendio.com>
#
# Copyright (C) 2008  Sven Herzberg
#
# This work is provided "as is"; redistribution and modification
# in whole or in part, in any medium, physical or electronic is
# permitted without restriction.
#
# This work is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# In no event shall the authors or contributors be liable for any
# direct, indirect, incidental, special, exemplary, or consequential
# damages (including, but not limited to, procurement of substitute
# goods or services; loss of use, data, or profits; or business
# interruption) however caused and on any theory of liability, whether
# in contract, strict liability, or tort (including negligence or
# otherwise) arising in any way out of the use of this software, even
# if advised of the possibility of such damage.

. demo.config

# start dbus daemon
eval `(cd ${top_builddir} && dbus-launch --sh-syntax --config-file=$(pwd)/demo/session.conf)`

# FIXME: copy trap stuff from https://stage.maemo.org/svn/maemo/projects/haf/branches/dbus/0.61-osso2/tools/run-with-tmp-session-bus.sh

# start demo client
./client

# kill dbus daemon
#kill $DBUS_SESSION_BUS_PID

